SDCICD-400. Add in link to grafana results to sd-scale job.
The sd-scale job now outputs a link to the expected grafana results of
the job.

diff --git a/resources/jenkins/sd-scale/job-templates.yaml b/resources/jenkins/sd-scale/job-templates.yaml
--- a/resources/jenkins/sd-scale/job-templates.yaml
+++ b/resources/jenkins/sd-scale/job-templates.yaml
@@ -83,8 +83,35 @@
           exit 1
         fi
 
+        # Check the validity of the cluster expiry
+        if ! echo "$EXPIRY_IN_MINUTES" | grep -qE "^[0-9]+$"; then
+          echo "Invalid expiry in minutes: expiry in minutes is malformed, should be a number."
+          exit 1
+        fi
+
+        if [ "$EXPIRY_IN_MINUTES" -lt "0" ]; then
+          echo "Invalid expiry in minutes: expiry in minutes needs to be greater than or equal to zero."
+          exit 1
+        fi
+
         echo "Running $SCALE_TEST_TYPE test..."
 
         mkdir report
         docker pull quay.io/app-sre/osde2e
+
+        NUM_BATCHES=$(( ($NUMBER_OF_CLUSTERS + ($SIZE_OF_BATCHES - 1)) / $SIZE_OF_BATCHES ))
+        ALL_CLUSTERS_PROVISIONED_SECONDS=$(( $NUM_BATCHES * $SECONDS_BETWEEN_BATCHES ))
+        TIME_UNTIL_ALL_CLUSTERS_EXPIRED=$(( $ALL_CLUSTERS_PROVISIONED_SECONDS + $EXPIRY_IN_MINUTES * 60 ))
+
+        if [ "$EXPIRY_IN_MINUTES" = "0" ]
+        then
+          # If the expiry is set to 0, just use a hardcoded 6 hours.
+          TIME_UNTIL_ALL_CLUSTERS_EXPIRED="21600"
+        fi
+
+        START_TIMESTAMP="$(date +%s%3N)"
+        END_TIMESTAMP="$(date -d "+$TIME_UNTIL_ALL_CLUSTERS_EXPIRED seconds" +%s%3N)"
+
+        echo "Check for results at https://grafana.app-sre.devshift.net/d/sd-scale/service-delivery-scale?from=$START_TIMESTAMP&to=$END_TIMESTAMP"
+
         docker run -u "$(id -u)" -e OCM_TOKEN -e "REPORT_DIR=/report" -e "CLUSTER_EXPIRY_IN_MINUTES=$EXPIRY_IN_MINUTES" -e "OCM_USER_OVERRIDE=ci-ext-jenkins" -v "$(pwd)/report:/report" --entrypoint osde2ectl quay.io/app-sre/osde2e create --configs stage -n $NUMBER_OF_CLUSTERS -b $SIZE_OF_BATCHES -s $SECONDS_BETWEEN_BATCHES
