Bayesian preview ci v4.. why can't i find the production gremlin stuff? BECAUSE IT DOESNT EXIST.

diff --git a/resources/jenkins/ci-centos/defaults.yaml b/resources/jenkins/ci-centos/defaults.yaml
--- a/resources/jenkins/ci-centos/defaults.yaml
+++ b/resources/jenkins/ci-centos/defaults.yaml
@@ -1158,6 +1158,26 @@
                 - '{build_branch}'
     <<: *job_template_build_defaults
 
+- job-template: &job_template_build_master-v4
+    name: '{ci_project}-{git_repo}-build-master-v4'
+    wrappers:
+      - vault-secrets:
+          <<: *vault_defaults
+          secrets:
+            - *kube-config-dsaas-stg-v4
+            - *quay-credentials
+            - *quay-eclipse-che-credentials
+            - *quay-che-incubator-credentials
+            - *registry-devshift-credentials
+            - *eclipse-che-github-packages-credentials
+    scm:
+        - git:
+            url: https://github.com/{git_organization}/{git_repo}.git
+            shallow_clone: true
+            branches:
+                - '{build_branch}'
+    <<: *job_template_build_defaults
+
 - job-template:
     name: '{ci_project}-{git_repo}-{subdir}-build-master'
     <<: *job_template_build_master
@@ -1199,6 +1219,115 @@
 
 - job-template:
     name: '{ci_project}-{git_repo}-f8a-build-master'
+    wrappers:
+      - vault-secrets:
+          <<: *vault_defaults
+          secrets:
+            - *quay-credentials
+            - *registry-devshift-credentials
+            - *recommender-api-token-prod
+      - ansicolor
+    scm:
+        - git:
+            url: https://github.com/{git_organization}/{git_repo}.git
+            shallow_clone: true
+            branches:
+                - master
+    skip_deploy: 0
+    deployment_units: ''
+    deployment_configs: ''
+    extra_target: ''
+    builders:
+        - shell: |
+            # testing out the cico client
+            set +e
+            set +x
+            export CICO_API_KEY=$(cat ~/duffy.key )
+            # get node
+            n=1
+            while true
+            do
+                cico_output=$(cico node get -f value -c ip_address -c comment)
+                if [ $? -eq 0 ]; then
+                    read CICO_hostname CICO_ssid <<< $cico_output
+                    if  [ ! -z "$CICO_hostname" ]; then
+                        # we got hostname from cico
+                        break
+                    fi
+                    echo "'cico node get' succeed, but can't get hostname from output"
+                fi
+                if [ $n -gt 15 ]; then
+                    # give up after 15 tries
+                    echo "giving up on 'cico node get'"
+                    exit 1
+                fi
+                echo "'cico node get' failed, trying again in 60s ($n/15)"
+                n=$[$n+1]
+                sleep 60
+            done
+            echo 'Using Host' $CICO_hostname
+
+            export DEVSHIFT_TAG_LEN=7
+
+            (
+                # run in subshell not to affect current environment
+                set +x
+
+                # load creds_config_file
+                eval "$(sed '/^\s*$/d;s/^/export /' $creds_config_file)"
+
+                cp ~/cico-tools/env-toolkit .
+                ./env-toolkit dump -f jenkins-env.json
+                env > jenkins-env
+            )
+
+            set -x
+
+            sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
+            ssh_cmd="ssh $sshopts $CICO_hostname"
+            $ssh_cmd yum -y install rsync
+            rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload
+            $ssh_cmd -t "cd payload && {ci_cmd}"
+            rtn_code=$?
+
+            # RHEL build
+            if [[ $rtn_code -eq 0 && -n "{extra_target}" ]]; then
+                $ssh_cmd -t "cd payload && TARGET=\"{extra_target}\" {ci_cmd}"
+                rtn_code=$?
+            fi
+
+            # We want to reuse the node for running E2E tests,
+            # but only if we are not doomed already.
+            if [[ $rtn_code -ne 0 || {skip_deploy} -ne 0 ]]; then
+                cico node done $CICO_ssid
+            fi
+
+            # Dump params for deploy-e2e-test-params
+            cat > deploy-e2e-test-params << EOF
+            GIT_ORGANIZATION={git_organization}
+            UPSTREAM_GIT_COMMIT=$GIT_COMMIT
+            SAAS_GIT={saas_git}
+            DEPLOYMENT_UNITS={deployment_units}
+            DEPLOYMENT_CONFIGS={deployment_configs}
+            CICO_HOSTNAME=$CICO_hostname
+            CICO_SSID=$CICO_ssid
+            EOF
+
+            exit $rtn_code
+        - conditional-step:
+            condition-kind: shell
+            condition-command: |
+                [[ {skip_deploy} -eq 0 ]] && exit 0 || exit 1
+            steps:
+                - trigger-builds:
+                    - project:
+                        - "devtools-f8a-master-deploy-e2e-test"
+                      property-file: deploy-e2e-test-params
+                      block: true
+    <<: *job_template_build_defaults
+
+- job-template:
+    name: '{ci_project}-{git_repo}-f8a-build-master-v4'
     wrappers:
       - vault-secrets:
           <<: *vault_defaults
@@ -4363,7 +4492,7 @@
             timeout: '1h'
             registry: 'quay.io'
             image_name: 'openshiftio/rhel-bayesian-gremlin'
-        - '{ci_project}-{git_repo}-f8a-build-master':
+        - '{ci_project}-{git_repo}-f8a-build-master-v4':
             git_organization: fabric8-analytics
             git_repo: gremlin-docker
             ci_project: 'devtools'
@@ -5766,7 +5895,7 @@
             ci_project: 'devtools'
             ci_cmd: '/bin/bash .ci/cico_compatibility_build_check.sh'
             timeout: '1h'
-        - '{ci_project}-{git_repo}-build-master':
+        - '{ci_project}-{git_repo}-build-master-v4':
             git_organization: kubesecurity
             git_repo: osa-api-server
             saas_git: saas-analytics
