clear cache automatically for push-saas-metrics
when push-saas-metrics fails, sometimes the fix is to just delete the
cache, therefore doing that automatically.

diff --git a/resources/jenkins/app-sre/job-templates.yaml b/resources/jenkins/app-sre/job-templates.yaml
--- a/resources/jenkins/app-sre/job-templates.yaml
+++ b/resources/jenkins/app-sre/job-templates.yaml
@@ -268,6 +268,20 @@
             -v $PWD/.cache:/cache:z \
             -v $PWD/.home:/root:z \
             quay.io/app-sre/push-saas-metrics:latest
+
+        rc="$?"
+
+        # remove cache if the job failed
+        if [ "$rc" != "0" ]; then
+            docker run --rm \
+                -e CACHE_DIR=/cache \
+                -v $PWD/.cache:/cache:z \
+                quay.io/app-sre/push-saas-metrics:latest \
+                find /cache -mindepth 1 -delete
+        fi
+
+        exit $rc
+
     cron_expression: H * * * *
     <<: *timed_template
 
