Test app-sre member check for hack folder changes
Signed-off-by: Di Wang <dwan@redhat.com>

diff --git a/data/services/app-interface/cicd/ci-int/jobs.yaml b/data/services/app-interface/cicd/ci-int/jobs.yaml
--- a/data/services/app-interface/cicd/ci-int/jobs.yaml
+++ b/data/services/app-interface/cicd/ci-int/jobs.yaml
@@ -58,6 +58,41 @@ config:
         timeout: 120
 
 - project:
+    name: app-interface-dwan-test
+    label: app-interface
+    node: app-interface
+    gl_group: dwan
+    gl_project: app-interface
+    environment: test
+    jobs:
+    # This job is for testing changes to gl-pr-check-app-interface
+    - 'gl-pr-check-app-interface':
+        display_name: schema validator pr-check manual testing
+        concurrent_build: true
+        # This is a temporary workaround to prevent changes to the hack directory from running MR checks
+        pr_check_script_path: |
+            if ! git diff --quiet origin/master HEAD -- ./hack/; then
+              echo "Checking permission for user: ${gitlabMergedByUser} ..."
+              GITLAB_API_URL=https://gitlab.cee.redhat.com/api/v4
+              USER_ID=$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" ${GITLAB_API_URL}/users?username="${gitlabMergedByUser}" | jq '.[0].id')
+              if [ "$USER_ID" == "null" ]; then
+                echo "User ${gitlabMergedByUser} not found!"
+                exit 2
+              fi
+
+              echo "Checking if user ${gitlabMergedByUser} (${USER_ID}) is a member of app-sre ..."
+              STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" ${GITLAB_API_URL}/groups/app-sre/members/"${USER_ID}")
+              if [ "$STATUS_CODE" == "200" ]; then
+                echo "Found authorized hack/ folder change, MR will run."
+              else
+                echo "Found unauthorized hack/ folder change, MR will not run."
+                exit 2
+              fi
+            fi
+            ./hack/pr_check.sh
+        job_type: '-manual-testing'
+
+- project:
     name: qontract-api
     label: app-interface
     node: app-interface
